"""Catálogo curado de emojis para o seletor de ícones.

Cada item é ``(emoji, "palavras-chave para busca")`` — em português (e alguns
termos em inglês), focado em usos de um lançador de atalhos: trabalho, tech,
web, ferramentas, símbolos de status, setas, etc.

Não é a lista completa de Unicode (seria enorme); é uma seleção prática. O
usuário também pode colar qualquer emoji manualmente no campo de ícone.
"""

from __future__ import annotations

from typing import List, Tuple

#: Grupos exibidos como seções no seletor: (título, [(emoji, keywords)...]).
EMOJI_GROUPS: List[Tuple[str, List[Tuple[str, str]]]] = [
    ("Trabalho", [
        ("💼", "trabalho maleta negocio work"),
        ("📁", "pasta folder arquivo"),
        ("📂", "pasta aberta folder open"),
        ("🗂️", "pastas divisorias organizar"),
        ("📅", "calendario data agenda"),
        ("📆", "calendario data"),
        ("🗓️", "calendario planner agenda"),
        ("📋", "prancheta clipboard lista"),
        ("📌", "alfinete fixar pin"),
        ("📎", "clipe anexo attach"),
        ("📝", "nota escrever memo documento"),
        ("📄", "documento pagina arquivo"),
        ("📃", "documento pagina"),
        ("📑", "marcadores documento"),
        ("📊", "grafico barras dados relatorio"),
        ("📈", "grafico subindo crescimento"),
        ("📉", "grafico caindo queda"),
        ("🗃️", "arquivo caixa fichario"),
        ("🗄️", "arquivo gaveta"),
        ("✏️", "lapis escrever editar"),
        ("🖊️", "caneta escrever"),
        ("📖", "livro aberto ler"),
        ("📚", "livros biblioteca estudar"),
        ("🔖", "marcador bookmark"),
        ("🏷️", "etiqueta tag preco"),
        ("🧾", "recibo nota fiscal"),
        ("📇", "fichario contatos"),
    ]),
    ("Jurídico", [
        ("⚖️", "balanca justica juridico direito advogado lei"),
        ("👨‍⚖️", "juiz advogado justica"),
        ("👩‍⚖️", "juiza advogada justica"),
        ("📜", "pergaminho contrato lei documento"),
        ("🏛️", "tribunal predio governo instituicao"),
        ("✒️", "caneta tinta assinatura assinar"),
        ("🖋️", "caneta tinteiro assinar"),
        ("🗳️", "urna voto eleicao"),
        ("🔏", "cadeado seguro assinado"),
    ]),
    ("Tecnologia", [
        ("💻", "notebook laptop computador"),
        ("🖥️", "computador desktop monitor pc"),
        ("⌨️", "teclado keyboard"),
        ("🖱️", "mouse"),
        ("🖨️", "impressora printer"),
        ("💾", "disquete salvar save"),
        ("💿", "cd disco"),
        ("📀", "dvd disco"),
        ("🔌", "tomada plugue energia"),
        ("🔋", "bateria energia"),
        ("📱", "celular smartphone telefone"),
        ("🧑‍💻", "programador dev desenvolvedor"),
        ("👨‍💻", "programador dev homem"),
        ("👩‍💻", "programadora dev mulher"),
        ("🤖", "robo bot ia inteligencia artificial"),
        ("🛰️", "satelite rede"),
        ("🌐", "globo web internet rede site"),
        ("🖧", "rede network"),
    ]),
    ("Web & Busca", [
        ("🌍", "mundo globo terra europa"),
        ("🌎", "mundo globo terra america"),
        ("🌏", "mundo globo terra asia"),
        ("🧭", "bussola navegar direcao"),
        ("🔍", "busca lupa procurar search"),
        ("🔎", "busca lupa procurar direita"),
        ("🔗", "link corrente url"),
        ("📡", "antena satelite sinal"),
        ("📶", "sinal wifi rede"),
    ]),
    ("Comunicação", [
        ("📧", "email correio mensagem"),
        ("✉️", "envelope email carta"),
        ("📨", "email recebido"),
        ("📩", "email enviado"),
        ("💬", "balao chat conversa mensagem"),
        ("🗨️", "balao fala"),
        ("📣", "megafone anunciar"),
        ("📢", "alto falante anuncio"),
        ("🔔", "sino notificacao aviso"),
        ("🔕", "sino mudo silenciar"),
        ("📞", "telefone ligar chamada"),
        ("☎️", "telefone fixo"),
        ("📲", "celular chamada seta"),
    ]),
    ("Mídia", [
        ("🎵", "musica nota som"),
        ("🎶", "musica notas som"),
        ("🎧", "fone headphone audio"),
        ("🎬", "cinema claquete filme video"),
        ("🎥", "camera filme video"),
        ("📷", "camera foto"),
        ("📸", "camera flash foto"),
        ("📹", "filmadora video"),
        ("📺", "tv televisao"),
        ("🎮", "jogo game controle"),
        ("🕹️", "joystick game arcade"),
        ("🎨", "arte paleta pintura design"),
        ("🖼️", "quadro imagem foto moldura"),
        ("🎤", "microfone cantar podcast"),
    ]),
    ("Ferramentas", [
        ("🛠️", "ferramentas martelo chave"),
        ("🔧", "chave inglesa ajustar config"),
        ("🔨", "martelo build"),
        ("⚙️", "engrenagem config configuracao settings"),
        ("🧰", "caixa ferramentas"),
        ("🔩", "parafuso porca"),
        ("🪛", "chave fenda parafuso"),
        ("🧲", "ima magnetico"),
        ("🧪", "tubo ensaio teste lab"),
        ("🔬", "microscopio ciencia lab"),
        ("🔭", "telescopio astronomia"),
        ("🧑‍🔧", "mecanico tecnico"),
    ]),
    ("Status & Símbolos", [
        ("⭐", "estrela favorito"),
        ("🌟", "estrela brilho destaque"),
        ("✨", "brilho estrelas novo"),
        ("⚡", "raio energia rapido flash"),
        ("🔥", "fogo quente hot trend"),
        ("💡", "lampada ideia dica"),
        ("✅", "check certo ok concluido verde"),
        ("☑️", "check marcado caixa"),
        ("✔️", "check certo confirmado"),
        ("❌", "x erro errado cancelar"),
        ("⛔", "proibido bloqueado"),
        ("🚫", "proibido nao"),
        ("⚠️", "aviso atencao alerta cuidado"),
        ("❗", "exclamacao importante"),
        ("❓", "duvida pergunta ajuda"),
        ("➕", "mais adicionar novo"),
        ("♻️", "reciclar renovar loop"),
        ("🔒", "cadeado fechado seguro bloqueado"),
        ("🔓", "cadeado aberto desbloqueado"),
        ("🔑", "chave senha acesso"),
        ("🗝️", "chave antiga acesso"),
        ("🛡️", "escudo seguranca protecao"),
        ("🏆", "trofeu vencedor premio"),
        ("🥇", "medalha ouro primeiro"),
        ("🎁", "presente gift"),
        ("🎉", "festa comemoracao"),
        ("💯", "cem nota maxima top"),
    ]),
    ("Setas & Player", [
        ("⬆️", "seta cima up"),
        ("⬇️", "seta baixo down"),
        ("⬅️", "seta esquerda left"),
        ("➡️", "seta direita right"),
        ("🔄", "atualizar recarregar refresh sync"),
        ("🔁", "repetir loop"),
        ("▶️", "play iniciar executar"),
        ("⏸️", "pausar pause"),
        ("⏹️", "parar stop"),
        ("⏭️", "proximo next"),
        ("⏮️", "anterior previous"),
        ("🔀", "aleatorio shuffle"),
    ]),
    ("Lugares & Transporte", [
        ("🏠", "casa home inicio"),
        ("🏡", "casa jardim home"),
        ("🏢", "predio escritorio empresa"),
        ("🏦", "banco financeiro"),
        ("🏬", "loja shopping"),
        ("🏭", "fabrica industria"),
        ("🚀", "foguete rocket lancar rapido deploy"),
        ("✈️", "aviao viagem voo"),
        ("🚗", "carro automovel"),
        ("🚚", "caminhao entrega"),
        ("🚢", "navio barco"),
        ("🗺️", "mapa localizacao"),
        ("📍", "pin localizacao lugar"),
        ("🚩", "bandeira marcar flag"),
        ("🏁", "bandeira chegada fim final"),
    ]),
    ("Dinheiro & Diversos", [
        ("💰", "dinheiro saco money"),
        ("💵", "dinheiro dolar nota"),
        ("💳", "cartao credito pagamento"),
        ("🪙", "moeda dinheiro"),
        ("🏧", "caixa eletronico atm"),
        ("📦", "caixa pacote entrega box"),
        ("🎒", "mochila bag"),
        ("🗑️", "lixeira excluir deletar"),
        ("⏰", "despertador alarme hora"),
        ("⏱️", "cronometro tempo"),
        ("⌛", "ampulheta tempo espera"),
        ("🕐", "relogio hora tempo"),
        ("☕", "cafe bebida"),
        ("🍵", "cha bebida"),
        ("🍕", "pizza comida"),
        ("🔦", "lanterna luz"),
        ("🔆", "brilho luz claro"),
        ("🌙", "lua noite escuro"),
        ("☀️", "sol dia claro"),
        ("🌈", "arco iris cores"),
        ("🧿", "amuleto protecao"),
        ("🔮", "bola cristal magia previsao"),
        ("🎲", "dado sorte aleatorio"),
        ("🧠", "cerebro mente ideia ia"),
        ("👀", "olhos ver observar"),
        ("👍", "joia curtir like positivo"),
        ("🎯", "alvo meta objetivo foco"),
        ("😀", "rosto sorriso feliz"),
        ("😎", "oculos legal cool"),
    ]),
]

#: Lista achatada de todos os emojis (emoji, keywords).
EMOJIS: List[Tuple[str, str]] = [item for _title, items in EMOJI_GROUPS for item in items]
